### ISSUE TITLE
Motis Test Servers not working

### ISSUE THREAD

**Issue by StephanAd** [motis-project/motis#101]
I just wanted to ask what about the test servers of Motis. Will they come back online in the foreseeable future?
For example, https://switzerland.motis-project.de/ and https://delfi.motis-project.de/ provide error code 503. The test servers of Berlin-Brandenburg and Aachen show a web overlay but have no functionality.

**Comment by felixguendling** [comment]
We merged Switzerland and DELFI and added the FlixBus timetable. The new URL is [europe.motis-project.de](https://europe.motis-project.de). Switzerland and DELFI URLs should redirect to Europe. We plan an adding more datasets in future. There was an error when booting the server (double time adjustment for timezones). The server is now running with a modified version where the check is commented out. Thank you for noticing.
