### ISSUE TITLE
only show Routes on foot, by bicycle or by car

### ISSUE THREAD

**Issue by StephanAd** [motis-project/motis#104]
Is it possible to get a single-mode route (e.g. a route entirely on feet/bicycle, without public transport)? If so, how can one do this, via the GUI or the API? As far as I can see the demo always shows public transport within the route, unless the route itself is short and too far from a station.

**Comment by felixguendling** [comment]
The Web UI currently shows single-mode routes when the source radius and the destination radius of a transport mode intersect. If you choose 30min source radius for car and 30min destination radius for car you get direct car connections up to 60min (if not dominated by public transport which is almost never the case).

If you would like to compute single-mode connections with the API you can use a OSRM request: https://github.com/motis-project/motis/blob/master/protocol/osrm/OSRMViaRouteRequest.fbs
That's what MOTIS uses internally for street routing, too. For pedestrian routing, you can use the PPR API: https://motis-project.de/docs/api/endpoint/ppr.html#pedestrian-routing-request

**Comment by StephanAd** [comment]
Thanks your answer is perfectly clear to me. I will close this issue.
