### ISSUE TITLE
GTFS2020 does not seem to work

### ISSUE THREAD

**Issue by StephanAd** [motis-project/motis#105]
Using the "older" GTFS data from here: https://opentransportdata.swiss/de/dataset/timetable-2020-gtfs seems to work without Problems. I've also tried to use the new format GTFS2020 from here: https://opentransportdata.swiss/de/dataset/timetable-2020-gtfs2020 which results in an error message "Verify fail schedule not loaded". Opentransportdata.swiss recommended switching to the new format by the end of July for example.

Are you aware of this behaviour? Are there plans to support the format in the future?

**Comment by StephanAd** [comment]
It was a mistake on my part that I cannot replicate. 
I used the data from here https://opentransportdata.swiss/de/dataset/timetable-2021-gtfs2020 and it works as intended. That is why I am closing the topic.

**Comment by felixguendling** [comment]
Strange thing is: I also had an issue starting a server with the dataset at the time of you opening this report but forgot to come back to you and look into the source of the problem. But if it's working now, that's fine, too. Feel free to open another issue anytime you encounter a problem. Thank you for giving us feedback.
