### ISSUE TITLE
Newest buildcache incompatible to Docker build image

### ISSUE THREAD

**Issue by Toboi** [motis-project/motis#108]
The newest release v0.23.0 of [buildcache](https://github.com/mbitsnbites/buildcache/) requires GLIBC 2.29, while the `motisproject/cpp-build:latest` docker image provides only GLIBC 2.27.
As the motis build process downloads the newest release of buildcache, this breaks the linux development workflow described [here](https://github.com/motis-project/motis/wiki/Linux-Developer-Setup).

Build Log: [build_log.txt](https://github.com/motis-project/motis/files/5611018/build_log.txt)

I could provide a PR fixing the buildcache version to v0.22.3 (the latest working release), but maybe a better solution would be including a working buildcache version within the docker image.

**Comment by pablohoch** [comment]
This should now be fixed by #109, which uses buildcache v0.22.3. Thank you for reporting the problem.
