### ISSUE TITLE
Illegal instruction (core dumped) on ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by Tim-Ganther** [motis-project/motis#113]
Hi,

I am trying to install the motis demo following the official documentation but unfortunatly when executing motis I am promted with the following error: `Illegal instruction (core dumped)`.
The system itself is a ubuntu 18.04.5 LTS virtual machine (4 cores, 16g ram, 64g storage) on a proxmox host - kvm virtualized.

**Comment by felixguendling** [comment]
Thank you for trying out MOTIS. Crashing is unfortunate. Do you have hardware support for virtualization enabled?
If this does not help, it would be interesting to know which instruction crashes the program. Could you please start MOTIS in `gdb` to get the instruction in question?

**Comment by Tim-Ganther** [comment]
Thanks for the fast reply! hv-evmcs is unfortunatly not supported by the kernel. Starting MOTIS in gdb returns the following output:
![image](https://user-images.githubusercontent.com/56401549/110184974-7953a200-7e11-11eb-9140-39e4f3515fea.png)

**Comment by felixguendling** [comment]
You can print the actual instructions like this: https://stackoverflow.com/a/2015523

**Comment by Tim-Ganther** [comment]
Okay, this actually returns:
```

  lqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk
  >x0x5555556cc39c  vmovdqu 0x1b9db5c(%rip),%xmm0        # 0x555557269f00      x
   x0x5555556cc3a4  vmovups %xmm0,(%r12)                                       x
   x0x5555556cc3aa  test   %rax,%rax                                           x
   x0x5555556cc3ad  je     0x5555556cc3be                                      x
   x0x5555556cc3af  cmpq   $0x0,0x1506b99(%rip)        # 0x555556bd2f50        x
   x0x5555556cc3b7  je     0x5555556cc3d0                                      x
   x0x5555556cc3b9  lock addl $0x1,0x8(%rax)                                   x
   x0x5555556cc3be  add    $0x8,%rsp                                           x
   x0x5555556cc3c2  mov    %r12,%rax                                           x
   x0x5555556cc3c5  pop    %rbp                                                x
   x0x5555556cc3c6  pop    %r12                                                x
   x0x5555556cc3c8  retq                                                       x
   x0x5555556cc3c9  nopl   0x0(%rax)                                           x
   x0x5555556cc3d0  addl   $0x1,0x8(%rax)                                      x
   x0x5555556cc3d4  add    $0x8,%rsp                                           x
   x0x5555556cc3d8  mov    %r12,%rax                                           x
   x0x5555556cc3db  pop    %rbp                                                x
   x0x5555556cc3dc  pop    %r12                                                x
   x0x5555556cc3de  retq                                                       x
   x0x5555556cc3df  nop                                                        x
   x0x5555556cc3e0  mov    $0x1,%edi                                           x
   x0x5555556cc3e5  callq  0x5555555fe8f0 <_Znwm@plt>                          x
   x0x5555556cc3ea  mov    $0x18,%edi                                          x
   x0x5555556cc3ef  mov    %rax,0x1b9db0a(%rip)        # 0x555557269f00        x
   x0x5555556cc3f6  mov    %rax,%rbp                                           x
   x0x5555556cc3f9  movq   $0x0,0x1b9db04(%rip)        # 0x555557269f08        x
   mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj
multi-thre Thread 0x7ffff7fea8 In:                     L??   PC: 0x5555556cc39c

```

**Comment by felixguendling** [comment]
Maybe AVX2 is not enabled on platforms without hardware virtualization support. I'll setup a build with `-DMOTIS_AVX=Off` CMake flag. The build will probably take a while to complete. If you don't want to wait for the slow GitHub Actions CI build, you can build it from source on your machine using `-DMOTIS_AVX=Off`.

**Comment by felixguendling** [comment]
I'm trying to build a version without AVX on the `noavx-ci` branch (PR #114).
It would be really helpful if you could try the build artifact. I'll post the link here when it's finished.

**Comment by Tim-Ganther** [comment]
Thank you, I'll definitly give it a shot tomorrow - but its already getting late.

**Comment by felixguendling** [comment]
Sure. Build will probably run ~1h 20min anyway :see_no_evil:

**Comment by felixguendling** [comment]
It's done:
Overview: https://github.com/motis-project/motis/actions/runs/625986738
No AVX Linux executable: https://github.com/motis-project/motis/suites/2191227783/artifacts/45204319

This is the current `master` branch build. The configuration for the import module has changed in order to support loading multiple timetables (https://europe.motis-project.de has DELFI, SBB and FlixBus/Train).

Our full configuration for the demo server as an example:
```ini
modules=tripbased
modules=intermodal
modules=ppr
modules=parking
modules=osrm
modules=lookup
modules=railviz
modules=address
modules=guesser
modules=path
modules=routing

dataset.num_days=3
#dataset.begin=20200818
dataset.begin=20201019
server.static_path=/root/motis-delfi/motis/web

[intermodal]
router=tripbased

[railviz]
tiles_redirect=https://t.motis-project.de/tiles/

[import]
paths=schedule-delfi:/root/motis-delfi/data/gtfs-delfi
paths=schedule-flix:/root/motis-delfi/data/gtfs-flixbus
paths=schedule-sbb:/root/motis-delfi/data/hrd-sbb
paths=osm:/root/motis-delfi/data/dach-200728.osm.pbf
data_dir=/root/motis-delfi/data

[osrm]
profiles=/root/motis-delfi/motis/osrm-profiles/car.lua
profiles=/root/motis-delfi/motis/osrm-profiles/bike.lua
profiles=/root/motis-delfi/motis/osrm-profiles/bus.lua

[ppr]
profile=/root/motis-delfi/motis/ppr-profiles/default.json
edge-rtree-max-size=10000000000

[parking]
import.edge_rtree_max_size=10000000000
```

If you just have one timetable schedule, `--import.paths path/to/your/timetable_folder` should work.

**Comment by Tim-Ganther** [comment]
It seems to work now - thank you very much. Btw I guess referencing this full config within the Installation Instructions as an example would help alot.

**Comment by felixguendling** [comment]
The config is for the current development version which is incompatible to the release version (for which the documentation is made). We'll update the documentation with the example with the next release. Thank you for reporting the problem with non-AVX platforms.

**Comment by laem** [comment]
Thanks for this development, I wasn't able to install the regular release on a Scaleway.com elastic metal, but the  motis-linux-amd64-noavx.tar.bz2  build works.
