### ISSUE TITLE
Docker health check probe for indicating "readiness"

### ISSUE THREAD

**Issue by mariodavid** [motis-project/motis#213]
Hi,

in order to run the motis container in a container scheduler (like ECS in my case), it is required to know when the motis container is treated as healthy / started.

With the initial calculations that are performed at container startup, it can reach the limit of waiting time.

What would you suggest to use for the Docker [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#healthcheck) command in order to identify if the container is ready? Is it enough to simply wait for `curl localhost:8080` or even rely on the load balancers' built-in health check to ask for an HTTP 200 on a particular path?

Or would you instead suggest doing something else inside the container with the HEALTHCHECK command?

PS: perhaps this is related to [my other question](https://github.com/motis-project/motis/issues/212#issuecomment-1055063666) since it is only really needed if the container takes multiple minutes to start as it has to do the initial calculations at startup. If it is possible to precalculate this and load it via an external volume, I would guess that this topic would not be necessarily a problem.

Thanks
Mario

**Comment by felixguendling** [comment]
At the moment, MOTIS does not have a specific health-check API or command. But since MOTIS only starts listening on the specified port after all the bootstrapping is done (so it's ready to respond to queries), this should work.

**Comment by felixguendling** [comment]
If you want to load only specific modules, you can put this into the `config.ini`:

```ini
modules=routing
modules=rt
modules=ris
modules=address
modules=guesser
modules=lookup
modules=railviz
modules=intermodal
modules=osrm
modules=ppr
modules=tiles
modules=path
modules=parking

intermodal.router=routing
```

This would be suitable for a real-time setup. There are different routers available (`tripbased`, `csa`, `raptor`, `routing`). Unfortunately, at the moment only the `routing` module is real-time capable. So it makes sense to disable all other routers and skip their import steps in a real-time scenario (e.g. with GTFS-RT).

In a static scenario, this setup would make sense:

```ini
modules=routing
modules=address
modules=guesser
modules=lookup
modules=railviz
modules=intermodal
modules=osrm
modules=ppr
modules=tiles
modules=path
modules=parking
modules=tripbased

intermodal.router=tripbased
```

The `ris` and `rt` modules are missing (not required in a static setup) and the routing can be done by the `tripbased` module which is way faster than the original `routing`. We're working on making one of those faster algorithms real-time compatible.

There's also an option to let `tripbased` route on the static timetable and then let the `intermodal` module update the journey data with real-time information. But this way, the results do not contain journeys that are only feasible in the current real-time situation.

**Comment by mariodavid** [comment]
> It is! You can run MOTIS with the --mode test flag which will not start listening on the port but just stop the server after all the import tasks are done. Running MOTIS a second time with the same volumes will lead to significantly lower startup times.

ok, this sounds exactly what I want. I will give it a try. I was thinking to have a (scheduled) container that pulls the OSM data and performs the calculation and writes it into the volume. Then a second container is actually responsible for serving the traffic. With what you described this should be doable.

Does that affect the whole `/data` volume, or is this only affecting particular files/subdirectories in there? I saw that e.g. there is also `/data/log` in there. Are these only the logs of the initialization or generally all container logs? Because there is also stuff going to SDTOUT as well.  In case it is for all logs, it might be required to put this into a dedicated directory, to not mix up the initialization container logs with the logs of the HTTP container.

**Comment by felixguendling** [comment]
The logs are currently only redirected to the `/data/log` folder during the import. After that, logging goes to standard output. However, MOTIS currently does not have a sophisticated logging in place. So this might change in the future (to be more configurable - for example to filter certain log levels, etc.).
