### ISSUE TITLE
Release 0.7.0 as docker image

### ISSUE THREAD

**Issue by mariodavid** [motis-project/motis#215]
Hi,

I saw that [0.7.0](https://github.com/motis-project/motis/releases/tag/v0.7.0) is out for two days, but currently, there is no docker image with the `0.7.0` tag (see: https://github.com/motis-project/motis/pkgs/container/motis/versions).

Could you release the current version as a docker container as well? Since I'm planning to use the docker installation, that would be a great help 👍 

Thanks

Mario

**Comment by felixguendling** [comment]
ghcr.io/motis-project/motis:0.7.1 points now to the latest release
