### ISSUE TITLE
Segfault during graph building

### ISSUE THREAD

**Issue by kalon33** [motis-project/motis#260]
Using this [GTFS dataset](https://eu.ftp.opendatasoft.com/sncf/gtfs/export-ter-gtfs-last.zip) with 0.8 version (amd64 with or without avx), I have a segfault:

```
     address: WAITING: {"OSM"}
        gbfs: WAITING: {"OSRM_BIKE", "OSRM_CAR", "OSRM_FOOT", "SCHEDULE"}
   osrm-bike: WAITING: {"OSM"}
    osrm-bus: WAITING: {"OSM"}
    osrm-car: WAITING: {"OSM"}
     parking: WAITING: {"OSM", "PPR", "SCHEDULE"}
parse sncf-ter: [■■■■                                                    ]   5% | Parse Calendar Dates
        path: WAITING: {"OSM", "OSRM", "SCHEDULE"}
      paxmon: WAITING: {"PAXMON_DATA", "SCHEDULE"}
         ppr: WAITING: {"OSM"}
    schedule: [■                                                       ]   0% | RUNNING
       tiles: WAITING: {"OSM"}
   tripbased: WAITING: {"SCHEDULE"}
Segmentation fault (core dumped)
```

Would it be possible to know why and eventually fix it?

**Comment by felixguendling** [comment]
Thank you for reporting this problem!

The parser could not deal with a CSV file that ends after the header.
Additionally, I added graceful handling of trips with no stop times that have a `block_id` set.

Will release version 0.8.1.

**Comment by felixguendling** [comment]
Release: https://github.com/motis-project/motis/releases/tag/v0.8.1
The CI will upload the release binaries in a few minutes.

**Comment by kalon33** [comment]
Thanks to you for the fix @felixguendling!
