### ISSUE TITLE
Connection not found

### ISSUE THREAD

**Issue by felixguendling** [motis-project/motis#272]
Investigate this bug:

![image](https://user-images.githubusercontent.com/1915889/184721479-c4531bbe-25a5-4a11-b300-2705466d553b.png)

**Comment by felixguendling** [comment]
Obviously just taking this IC 2072 from Berlin Hbf is the better option (later departure, saves one transfer). If this is not a data problem MOTIS should find a this instead.

**Comment by julianharbarth** [comment]
If you search from S Spandau Bhf (Berlin) you find the journey. 

Apparently, Spandau Bhf and S+U Berlin Hauptbahnhof are meta stations, so you actually get the journey starting at S+U at 09:06.

Maybe start label generation for S+U? IC2027 is the only IC serving S+U, but I don't think the start label generation takes departure event class as a parameter or similar.

**Comment by felixguendling** [comment]
Fixed by d90e87a6f6fd46599376165bc9d3df069f957e8f
