### ISSUE TITLE
Can I use multiple GTFS schedules for motis?

### ISSUE THREAD

**Issue by luckyhandler** [motis-project/motis#273]
My current import section in the config.ini looks like this 

```
[import]
paths=schedule:/input/schedule
paths=osm:/input/osm.pbf
data_dir=/data
```

Is it possible to add multiple schedules to the schedule path?

**Comment by felixguendling** [comment]
```
[import]
paths=schedule-delfi:/input/schedule/delfi
paths=schedule-nl:/input/schedule/nl
paths=schedule-swiss:/input/schedule/swiss
paths=osm:/input/osm.pbf
```

This is our `import` section for our `config.ini` at https://europe.motis-project.de
The format is `schedule-${tag}:${path}`.
