### ISSUE TITLE
0.11.4: Error: 10 already in shared_data

### ISSUE THREAD

**Issue by 1Maxnet1** [motis-project/motis#385]
I just wanted to update our motis server to version 0.11.4. Therefore (as usual) I do delete the old version and replace it with the new download and extracted archive. But after starting up motis again it fails with:
`nigiri: Error: 10 already in shared_data`

One of the imports failed: nigiri

I tried to add the match_duplicates option to the config.ini, but that didn't changed it.
Also I deleted the `core` file. Am I supposed to keep it? Before this update motis just regenerated it after some time, so I assumed it was okay to delete it, to avoid issues, due to keeping it.

I reverted back to 0.11.3 and it works again, but if you have any suggestions let me know, and I will give it a try.

**Comment by felixguendling** [comment]
Starting with v0.11.4 it's intended to use MOTIS with either the new core (nigiri module) or the old core (`dataset.*` options), not both at the same time.

So you can either use MOTIS without the `nigiri` module as before or you enable the `nigiri` module and use `dataset.no_schedule=true` to disable the old core.

To get writ of the error you encountered, you can apply `nigiri.lookup=false` which means that you probably want to turn on the `lookup` module which does the same based on the old core. But I would recommend to disable the old core completely by setting `dataset.no_schedule=true`.

Sorry for the confusion. Maybe we should at one point release v1.0 and then follow the semantic versioning requirements to not break API in minor versions.

**Comment by felixguendling** [comment]
> Also I deleted the `core` file

`core` files result from crashes. Since you probably use the release binary which does not contain any debug info, the core file does not contain any helpful information from the crash anyway. In this case it's obvious why MOTIS crashed so you can safely delete it. Most systems are configured in a way to not dump the core anyway.

**Comment by 1Maxnet1** [comment]
> But I would recommend to disable the old core completely by setting dataset.no_schedule=true.

I did so and was successful, thanks! 

> Sorry for the confusion. Maybe we should at one point release v1.0 and then follow the semantic versioning requirements to not break API in minor versions.

Totally agree. Especially if one wants to set up a production server, it seems to be necessary to know what configuration adaptions are needed before upgrading.
