### ISSUE TITLE
Outdated Wiki page about Subcommands / Tool

### ISSUE THREAD

**Issue by 1Maxnet1** [motis-project/motis#403]
I'm currently trying out the different sub-commands of MOTIS and try to follow the documentation given at https://github.com/motis-project/motis/wiki/Tools. However it seems to be outdated as names of arguments and sub-command names changed. (I'm using Version 0.11.6 while the documentation dates back to 2021). Do you have any more up-to-date documentation that you could publish? Else I'm going with the --help options and some Trail'n'Error to get it to work to my likings. If you want, I can offer to update the Wiki page accordingly, however the write access is currently restricted so I'm not able to edit it directly.

**Comment by felixguendling** [comment]
I tried to update it. Let me know if you find anything that doesn't work.

**Comment by 1Maxnet1** [comment]
> I tried to update it. Let me know if you find anything that doesn't work.

Thanks a ton for the quick update.

When I try:
```
sudo motis/motis generate -c generate-config.ini --message_type routing \                                                             IOT ✘ 
  --start_type ontrip_station \
  --dest_type station \
  --routers /nigiri /routing
```

I get the following error:
```
2023-10-30T13:42:19Z [VERIFY FAIL] 0 not in shared_data
terminate called after throwing an instance of 'std::runtime_error'
  what():  0 not in shared_data
```

Any idea about this?

**Comment by felixguendling** [comment]
Same problem as last time: you can't use the old and new core together.

This is the configuration I currently use.

```
# generator-config.ini (old core)
query_count=100
message_type=routing
start_type=pretrip
dest_type=station
routers=/nigiri
dataset.begin=20231028
import.paths=schedule-de:input/schedule/delfi
```

```# input/config.ini
# batch mode config (new core)
modules=nigiri
dataset.no_schedule=true
import.paths=schedule-de:input/schedule/delfi
nigiri.first_day=2023-10-28
mode=batch
batch_input_file=q_nigiri.txt
batch_output_file=r_nigiri.txt
```

`sudo` is not necessary to run evaluations, so I would do it as user.

**Comment by felixguendling** [comment]
`./motis/motis generate -c generator-config.ini`

`./motis/motis -c input/config.ini --batch_output_file r_nigiri.txt`

**Comment by 1Maxnet1** [comment]
> I tried to update it. Let me know if you find anything that doesn't work.

I was able to use the described commands, everything fine from my side now. Thanks a lot!
