### ISSUE TITLE
unable to import routing module

### ISSUE THREAD

**Issue by Aeris1One** [motis-project/motis#408]
Hi, I'm trying to run Motis on Rouen (Normandy) transportation system. (GTFS dataset : https://transport.data.gouv.fr/resources/64973)

I did follow "Installation and Setup"
```yaml
modules=intermodal
modules=address
modules=tiles
modules=osrm
modules=ppr
modules=parking
modules=nigiri

server.static_path=motis/web
dataset.no_schedule=true

[import]
paths=schedule-astuce:astuce.zip
paths=osm:haute-normandie.osm.pbf

[osrm]
profiles=motis/osrm-profiles/car.lua
profiles=motis/osrm-profiles/bike.lua

[ppr]
profile=motis/ppr-profiles/default.json

[tiles]
profile=motis/tiles-profiles/background.lua
```
and it works well, webui shows the map with estimated transport position but searching for an itinerary doesn't work because there aren't any intermodal router module loaded (`[dispatcher.cc:122] target not found: /routing`). So I tried to load "routing" module by adding "modules=routing", and had this error : 
```log
     address: FINISHED
      nigiri: FINISHED
   osrm-bike: FINISHED
    osrm-car: FINISHED
     parking: FINISHED
         ppr: FINISHED
     routing: WAITING: {"SCHEDULE"}
       tiles: FINISHED
2023-11-20T08:34:04Z [VERIFY FAIL] some imports were not successful: routing

initialization error: some imports were not successful: routing
```

I thought it would be related to `dataset.no_schedule=true` option, so I removed it, and now I have this one : 
```log
     address: FINISHED
      nigiri: FINISHED
   osrm-bike: FINISHED
    osrm-car: FINISHED
     parking: FINISHED
         ppr: FINISHED
     routing: WAITING: {"SCHEDULE"}
    schedule: WAITING: {"SCHEDULE"}
       tiles: FINISHED
2023-11-20T08:40:15Z [VERIFY FAIL] schedule not loaded

initialization error: schedule not loaded
```

I tried with `paths=schedule:astuce.zip` with `schedule` instead of `schedule-[tag]` and got `nigiri: ERROR: all schedules require a name tag, even with only one schedule`

How could I solve this ?

**Comment by Aeris1One** [comment]
Using `intermodal.router=nigiri` to use the `nigiri` new core as intermodal solves the problem

**Comment by felixguendling** [comment]
Thank you! I added it to the wiki page.
