### ISSUE TITLE
motis returns "exit code 0" even upon errors during startup

### ISSUE THREAD

**Issue by PartTimeDataScientist** [motis-project/motis#422]
While working on a setup where one instance of motis is preprocessing data for updating a live instance with minimal downtime I realized that my "preprocessing instance" of motis returns exit code `0` even if - in this case - some imports were not successful.

```
motis-motis-1  | 2023-12-17T23:13:20Z [VERIFY FAIL] some imports were not successful: gbfs, parking
motis-motis-1  | 
motis-motis-1  | initialization error: some imports were not successful: gbfs, parking
motis-motis-1 exited with code 0
```

It would be very helpful if motis returned exit codes that could be further processed (i.e. indicate the type of error) but at least I think it should not return `0` if anything went wrong during startup

**Comment by felixguendling** [comment]
After "initialization error", there is already `return 1`:
https://github.com/motis-project/motis/blob/a08542e3cd641cdbfd83e365f1b9f017643a121f/base/launcher/src/main.cc#L151-L154

**Comment by felixguendling** [comment]
For me, it gives exit code 1 in this situation:

```
➜  ./motis/motis
# ...
initialization error: some imports were not successful: routing
➜  motis-test echo $?      
1
```

**Comment by PartTimeDataScientist** [comment]
That's strange - while looking at the code you referenced I also saw that the imports are at the very start of the `try` block (if I understand the code correctly) - still I get exit code 0 in my dockerized case... :confused:

https://github.com/motis-project/motis/blob/a08542e3cd641cdbfd83e365f1b9f017643a121f/base/launcher/src/main.cc#L115-L116

**Comment by PartTimeDataScientist** [comment]
Could be the case that the motis error is not reflected in the docker container exit code? - I'll try to verify that...

**Comment by felixguendling** [comment]
I guess that's the only option. But I'm not a Docker expert. The Dockerfile looks pretty standard.

**Comment by PartTimeDataScientist** [comment]
Using `restart: no` in the `docker-compose.yml` file the error is transitioned upstream - that should at least work for my use case - I am still puzzled why this does not happen in the restart case.

Closing this issue as this then seems to be caused by docker handling the error (might even be a feature and not a bug). I'll update this issue if I learn more on that topic

```
motis-motis-1  | initialization error: some imports were not successful: gbfs, parking
motis-motis-1 exited with code 1
```
