### ISSUE TITLE
Clarify setup script for loading multiple GTFS / running just a transit server

### ISSUE THREAD

**Issue by laem** [motis-project/motis#424]
> Following the issue about the comparison to OpenTripPlanner #423 , in order to keep it focused. 

Loading the whole [GTFS agregate for the Bretagne region](https://transport.data.gouv.fr/datasets/base-de-donnees-multimodale-transports-publics-en-bretagne-mobibreizh-gtfs) + the regional train GTFS seems to fail because of GTFS stop errors. 3 examples below : 

```
nigiri: could not find avv_BIBUS:ST:AUTO$372029409, BIBUS:ST:AUTO$372029409, 0, tags: 0=avv_, 1=avv_
nigiri: could not find avv_MAT:ST:AUTO$509666393, MAT:ST:AUTO$509666393, 0, tags: 0=avv_, 1=avv_
nigiri: could not find avv_MAT:ST:AUTO$509666393, MAT:ST:AUTO$509666393, 0, tags: 0=avv_, 1=avv_
[erro][2024-01-05T16:05:14Z+0000][dispatcher.cc:128] error executing /nigiri: ankerl::unordered_dense::map::at(): key not found
```

**Edit :**

I was confused by the `schedule-avv` key in `paths=schedule-avv:FILE`. I thought it was some kind of generic key to label an imported file as GTFS. Hence the collision. 

I can't PR the Wiki, would gladly help document this, it's not that intuitive. 

This worked for me. 
```
[import]
paths=schedule-bretagne:input/bretagne.gtfs.zip
paths=schedule-ter:input/export-ter-gtfs-last.zip
paths=schedule-intercites:input/export-intercites-gtfs-last.zip
paths=schedule-tgv:input/export_gtfs_voyages.zip
paths=osm:input/bretagne.osm.pbf
```

This is the result for crossing the whole region from Rennes to Brest. Left is the official SNCF booking website. 

![image](https://github.com/motis-project/motis/assets/1177762/303cd081-5f1b-41a1-88dc-c1abb83080df)

And this for a trip inside the region's capital. 

![image](https://github.com/motis-project/motis/assets/1177762/a324d196-d1fd-4c0e-b30d-d5b736a603e1)

Here's a third comparison with the first metro line, the `A`. It is not proposed by Motis. 

![image](https://github.com/motis-project/motis/assets/1177762/a9d6c211-6557-4134-b431-cf4dc1409836)

Thanks for your help !

**Comment by felixguendling** [comment]
Looks great! I'll move the wiki files to the repository. Then PRs to improve the documentation will work.

**Comment by felixguendling** [comment]
Example for v2 for multiple GTFS datasets with GTFS-RT:
https://github.com/motis-project/motis/blob/master/docs/setup.md

(but old config.ini format is still supported for now with v2)
