### ISSUE TITLE
value of step_type has multiple types

### ISSUE THREAD

**Issue by ch33hau** [motis-project/motis#426]
Hi there, 

I have a question regarding the JSON response. 

According to the [doc](https://motis-project.de/docs/api/endpoint/ppr.html), `step_type` should be an enum in the string, but occasionally it returns a number. 
Is this an expected behavior? 

An example:
```
              {
                "step_type": 5,
                "street_name": "",
                "street_type": "NONE",
                "crossing_type": "GENERATED",
                "distance": 0.0,
                "duration": 0.0,
                "accessibility": 0.0,
                "path": {
                  "coordinates": [
                    52.534528,
                    13.196046
                  ]
                },
                "elevation_up": 0,
                "elevation_down": 0,
                "incline_up": false,
                "handrail": "UNKNOWN"
              },
```

**Comment by ch33hau** [comment]
In fact, the same also happens to `edge_type`:
```
              {
                "distance": 0.0,
                "duration": 0.0,
                "accessibility": 0.0,
                "path": {
                  "coordinates": [
                    52.567042,
                    13.411141,
                    52.567042,
                    13.411141
                  ]
                },
                "name": "",
                "osm_way_id": -4801304311,
                "edge_type": 5,
                "street_type": "NONE",
                "crossing_type": "GENERATED",
                "elevation_up": 0,
                "elevation_down": 0,
                "incline_up": true,
                "handrail": "UNKNOWN"
              },
```

**Comment by felixguendling** [comment]
I guess it's always an integer. Those are the values:

https://github.com/motis-project/motis/blob/a08542e3cd641cdbfd83e365f1b9f017643a121f/protocol/ppr/Route.fbs#L6
https://github.com/motis-project/motis/blob/a08542e3cd641cdbfd83e365f1b9f017643a121f/protocol/ppr/Route.fbs#L53-L59

They count up from zero.

**Comment by pablohoch** [comment]
We'll need to update the types in MOTIS and the docs. Some new step and edge types have recently been added to PPR.

**Comment by ch33hau** [comment]
They seems to be like strings for very long time. For example:
```
            "steps": [
              {
                "step_type": "FOOTWAY",
                "street_name": "",
                "street_type": "NONE",
                "crossing_type": "NONE",
                "distance": 0.023245,
                "duration": 0.016603,
                "accessibility": 0.0,
                "path": {
                  "coordinates": [
                    52.534668,
                    13.197191,
                    52.534668,
                    13.197191
                  ]
                },
                "elevation_up": 0,
                "elevation_down": 0,
                "incline_up": true,
                "handrail": "UNKNOWN"
              },
```

Also they are strings from the example in motis docs: https://motis-project.de/docs/api/endpoint/ppr.html

**Comment by ch33hau** [comment]
> We'll need to update the types in MOTIS and the docs. Some new step and edge types have recently been added to PPR.

So the valid one should be in Integer type? or will be fixed to only String type? or mixed types (the current behavior...)?

**Comment by pablohoch** [comment]
They should be strings. I forgot to add the new types to MOTIS, which is why they are currently returned as integers. I'll work on a fix that will add the new types - then they should be only strings again.

**Comment by ch33hau** [comment]
> They should be strings. I forgot to add the new types to MOTIS, which is why they are currently returned as integers. I'll work on a fix that will add the new types - then they should be only strings again.

I see, thanks a lot @felixguendling @pablohoch for the quick responses!

**Comment by ch33hau** [comment]
> The [fix](https://github.com/motis-project/motis/pull/427) is merged and the [docs](https://motis-project.de/docs/api/endpoint/ppr.html) are updated. We can publish a new release once the CI run is done.
> 
> The new edge and step types are for entrances (typically doors) and cycle barriers.
> 
> I've also updated PPR to the latest version. This new version also adds some preprocessing improvements regarding street crossings. Therefore, I would recommend deleting the `ppr` directory in your `data` directory before running the new MOTIS version. This will cause a re-import of the OSM file with the latest PPR version.

Thanks for the instructions, will do =)
