### ISSUE TITLE
Route color

### ISSUE THREAD

**Issue by laem** [motis-project/motis#429]
In the demo app, the color of routes depends on the route type (train, bus, fast train, etc.). 

However, `route_color` is a [standard attribute in GTFS timetables](https://gtfs.org/schedule/reference/#routestxt), that is essential to build UIs. 

Is there a way to pull this kind of attribute from the `intermodal` API request ? 

Alternatively, a route to expose the attributes of a GTFS route ? Or should we handle this kind of request using another GTFS parser API ?

**Comment by felixguendling** [comment]
At the moment, this is not implemented. The attribute is ignored while parsing and doesn't get stored anywhere. So currently, it cannot be exposed via the API. It's kind of a TODO without concrete schedule when it will be done. I guess it's not a big deal to implemented it but until now everyone was fine with the category based colouring.

**Comment by laem** [comment]
Thanks. I've implemented a small node server to pull these informations form the GTFS zip files. The server can be run easily on a PaaS platform (like scalingo). It requires followup requests after the Motis intermodal computation, but in practice that's fine, considering the speed of this node server. 

This route precisely https://github.com/laem/gtfs/blob/master/server.js#L76. 

Could be helpful for people with the same needs as mine, until it is implemented in Motis :)

**Comment by felixguendling** [comment]
Thank you for providing your solution! :+1:

**Comment by laem** [comment]
Well, after some tests : Motis parses 100 % of my ~7 GTFS files, while node-GTFS fails for 4 of them for various reasons. I might look into it.

**Comment by felixguendling** [comment]
MOTIS is not a validator. Our concept is "garbage in - garbage out". There are enough GTFS validation tools (and tools like [gtfs-tidy](https://github.com/patrickbr/gtfstidy)) out there that everyone can use to check for validity. MOTIS expects valid data but will not complain if it contains errors. Instead, MOTIS fixes everything that's required to have a valid routing graph. But for a production system, I would recommend to use a validator before passing data to MOTIS.

**Comment by laem** [comment]
Hi, after some looking around, I've found the... lookup module through the Wiki. 

It doesn't look well documented. I guess for now, the only documentation si the source code ? https://github.com/motis-project/motis/tree/master/modules/lookup/src

Which is quite fine, actually. Tests are also helpful. 

I'm trying to evaluate how easily I could bypass my node-GTFS dependency and go full motis. 

A colleague just made a pull request to node-GTFS adding lookup of stations by lat, lon. https://github.com/BlinkTagInc/node-gtfs/pull/152

It looks like Motis already has that with lookup/geo_station.

**Comment by felixguendling** [comment]
Yes, the geo station lookup is implemented (now in the `nigiri` module, `lookup` depends on the old core).

It's not really a documentation, but the `*Request` and `*Response` types are self-explanatory in most cases:
https://github.com/motis-project/motis/tree/master/protocol/lookup

Currently, only [LookupGeoStationRequest](https://github.com/motis-project/motis/blob/master/protocol/lookup/LookupGeoStationRequest.fbs) is implemented in `nigiri` but most other `lookup` requests would also be easy to implement using the nigiri data structures.

To have a more complete coverage of GTFS in the MOTIS API, attributes like `route_id`, `route_color`, shapes, etc. would need to be implemented in nigiri which is possbile but a bit more work.

**Comment by felixguendling** [comment]
> I'm trying to evaluate how easily I could drop my node-GTFS dependency and go full motis.

Which APIs are missing?

**Comment by laem** [comment]
> To have a more complete coverage of GTFS in the MOTIS API, attributes like route_id, route_color, shapes, etc. would need to be implemented in nigiri which is possbile but a bit more work.

Well for now, mostly this I guess. I've found node-GTFS since I mostly write JS code, and their documentation is quite good. I need to try a rewrite.

**Comment by laem** [comment]
Implemented in 
https://github.com/motis-project/nigiri/pull/67
