### ISSUE TITLE
Motis returns wrong classifications for public transportation means

### ISSUE THREAD

**Issue by luckyhandler** [motis-project/motis#432]
It seems that in motis 0.11.12 the returned public transportation means are not correctly classified.
The move entity contains at least for trams as well as for subways from Nuremberg to Fürth, Bavaria clazz 10 and name `Bus U1`.

**Comment by felixguendling** [comment]
This depends on the dataset.

If you think, the mapping from GTFS route type to MOTIS clasz is wrong, please propose a change to the mapping here:

https://github.com/motis-project/nigiri/blob/166411ed9e80347a5b51a34150dc11bda44f3c03/src/loader/gtfs/route.cc#L16-L120

**Comment by derhuerst** [comment]
> https://github.com/motis-project/nigiri/blob/166411ed9e80347a5b51a34150dc11bda44f3c03/src/loader/gtfs/route.cc#L16-L120

FYI: These seem to be the [*Google Extended Route Types*](https://developers.google.com/transit/gtfs/reference/extended-route-types).

**Comment by felixguendling** [comment]
Correct, thanks you!

We map those 80+ types to 10 to make it easier in the UI to display them. It would probably also not be a big deal to pass the exact route type number via the API, but to us the aggregated number ("clasz") was always more useful.

**Comment by luckyhandler** [comment]
Works with the latest GTFS data again. Thanks for the clarification and support.
