### ISSUE TITLE
Inconsistent error response from API call (missing _type)

### ISSUE THREAD

**Issue by GerdC** [motis-project/motis#454]
When my client calls an API, it either gets the expected JSON response or an error JSON like this:

```
{
  "_type": "MotisError",
  "error_code": 3,
  "category": "motis::module",
  "reason": "module: target not found"
} 

```
Described here https://europe.motis-project.de/openapi/#/schemas/motis.MotisErrorT

Both response types contain a "_type" property.

So after decoding "_type", the client can decide whether to decode the error or the expected response JSON.

My tests revealed one error message, that deviates from this pattern:

```
{
  "error": {
    "code": 422,
    "reason": "Unprocessable Entity",
    "description": "The request was well-formed but was unable to be followed due to semantic errors."
  }
}

```

There is no "_type", making it a little harder for a client to decide what to do with that response.

Am I wrong to expect a _type at the top level of a response JSON?
If not, returning an error with _type would be nice.

Reproduce
I got this error calling the intermodal routing API of Transitous.
It is ok that I get an error because intermodal routing is turned off currently.
This issue is just about the schema of this error JSON. (and maybe better error message. If I didn't know that intermodal routing was turned off, this error message would be unhelpful)

**Comment by felixguendling** [comment]
I can't find any code in MOTIS that produces this schema.
"Search in all files" for (parts of) the error string didn't find any results in the code base, neither in our `net` library or boost beast (the HTTP library we use).
I'm not sure if this error is coming from MOTIS?

**Comment by GerdC** [comment]
Oops. Then let's close it, might have to do something with Transitous.
