### ISSUE TITLE
HTTP content-encoding: gzip support for GTFS-RT fetching

### ISSUE THREAD

**Issue by vkrause** [motis-project/motis#473]
The Finish national railway feed insists on gzip content encoding, otherwise we get HTTP 406 "Please add http header "accept-encoding : gzip" to your request. Requests without compression are not allowed".

GTFS: https://rata.digitraffic.fi/api/v1/trains/gtfs-all.zip
GTFS-RT: https://rata.digitraffic.fi/api/v1/trains/gtfs-rt-updates

**Comment by felixguendling** [comment]
Maybe it makes sense to add the `Accept-Encoding: gzip` header to every request directly in `http_request_executor`.

**Comment by felixguendling** [comment]
I guess it would be sufficient to set the request header as the client implementation already handles gzip encoding:

https://github.com/motis-project/net/blob/785b39c08212732e510305f0eef18de70f19b15e/src/http/client/client.cc#L164-L178

**Comment by vkrause** [comment]
oh, indeed, I missed that!

**Comment by vkrause** [comment]
perfect, that works :)
