### ISSUE TITLE
Multiple questions,

### ISSUE THREAD

**Issue by gigz904** [motis-project/motis#476]
Hello !

Can I switch the lang of the web page from deutsch to english ?
Can I import multiple GTFS ?
And how i can use a GTFS-RT flux with a http link ?

Thanks,
RJ.

**Comment by felixguendling** [comment]
There's the `lang` URL parameter for switching languages: https://europe.motis-project.de/?lang=en

>  Can I import multiple GTFS ?

Yes. Example:

```ini
[import]
paths=osm:/input/osm.pbf
paths=coastline:/input/land-polygons-complete-4326.zip
paths=schedule-nl:/input/schedule/nl
paths=schedule-swiss:/input/schedule/swiss
```

You need to give every feed a unique tag (here: `nl, `swiss`, etc.) and specify that it's a schedule.

>  And how i can use a GTFS-RT flux with a http link ?

```ini
[nigiri]
gtfsrt=nl|http://gtfs.ovapi.nl/nl/tripUpdates.pb
gtfsrt=swiss|https://api.opentransportdata.swiss/gtfsrt2020|API_KEY
```

Use the exact tag from above and a link. Optionally you can add an API key that will be used set as HTTP header.
