### ISSUE TITLE
GTFS RT protobuf generation fails silently

### ISSUE THREAD

**Issue by waarmond** [motis-project/motis#481]
Dear devs,

I'm using protobuf 25.3 which is near to the version motis [uses for nigiri](https://github.com/protocolbuffers/protobuf/tree/690e03babf0963d3da9615a2dae0891777842719) but shouldn't play any role since the build has all dependencies vendored. After a 'long and successful build' with
```
  cmake .. \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DMOTIS_WITH_WEBUI=ON \
    -DMOTIS_AVX=ON \
    -DMOTIS_AVX2=ON

  make
```
it fails due to an empty gtfsrt dir, but displays no specific error:
```
[ 83%] Generating GTFS RT protocol buffers C++ code
./motis/build/deps/nigiri/generated/gtfsrt/: No such file or directory
make[2]: *** [deps/nigiri/CMakeFiles/gtfsrt.dir/build.make:75: deps/nigiri/generated/gtfsrt/gtfs-realtime.pb.h] Fehler 1
```

**Comment by felixguendling** [comment]
Can you try `-GNinja`?

I sometimes had issues with protobuf provided by the OS, so I would recommend to uninstall it if possible.

**Comment by waarmond** [comment]
Ninja build. How sad: `[1872/1872] Linking CXX executable motis`
```
[..]
/usr/bin/ld: deps/nigiri/libnigiri.a(init_finish.cc.o): in function `tbb::detail::d1::task_group_context::~task_group_context()':
init_finish.cc:(.text._ZN3tbb6detail2d118task_group_contextD2Ev[_ZN3tbb6detail2d118task_group_contextD5Ev]+0x16): undefined reference to `tbb::detail::r1::destroy(tbb::detail::d1::task_group_context&)'
```
Could this be a OneTBB 2019 [vs](https://gitlab.archlinux.org/archlinux/packaging/packages/usd/-/blob/main/usd-tbb.patch?ref_type=heads) 2021 incompatibility ? tbb seems not be locked.

**Comment by felixguendling** [comment]
Since *everything* is locked, also TBB is locked. We only support the exact dependency versions given in the tree via `.pkg` files with the exact environment given by this [Docker CI container](https://github.com/motis-project/docker-cpp-build). In general, GCC 12 and Clang 16 should work as this is what we use in the CI.

https://github.com/motis-project/osrm-backend/blob/a7fe58cf3b6a54968d1248e0b4299d49db02ff2e/.pkg#L8

https://github.com/motis-project/tbb/tree/b3011be5060ec1be43c76d4a8cc80d5550adb31d

**Comment by waarmond** [comment]
You are using TBB 2020 Update 2; there have been breaking changes to task_group_context.

Sorry for asking so much: Is motis doing a static build?

**Comment by felixguendling** [comment]
> Sorry for asking so much

No worries! :)

> Is motis doing a static build?

Yes. Everything else is not supported (as we've never tried it). The CI produces builds that are free of system libraries (as we use statically linked lib musl to replace glibc). For development (only), a dynamic linking build would be interesting to experiment with (to reduce linking times).
