### ISSUE TITLE
CSV parser doesn't correctly handle escaped quote characters

### ISSUE THREAD

**Issue by jbruechert** [motis-project/motis#494]
The station name parsed by MOTIS:
![image](https://github.com/motis-project/motis/assets/13609393/257c595e-5996-4633-90ca-3cc021574530)

The station name parsed by LibreOffice:
![image](https://github.com/motis-project/motis/assets/13609393/78787e71-2afe-4309-8d30-ce07b483a7f7)

The feed can be found here for testing:
https://routing.spline.de/gtfs/lv_valsts-sia-autotransporta.gtfs.zip

**Comment by felixguendling** [comment]
Should be fixed with v0.12. Did it work?

**Comment by felixguendling** [comment]
Closing as it should be fixed. Comment if not.
