### ISSUE TITLE
Walking past a first bus stop to the second, further

### ISSUE THREAD

**Issue by laem** [motis-project/motis#510]
Hi, I'm trying to debug this use case. 

In Brest, on the Europe instance https://europe.motis-project.de, from the train station to the "Iroise" mall. 

![Capture d’écran 2024-05-27 à 08 43 19](https://github.com/motis-project/motis/assets/1177762/bb294ec4-53cf-4bec-b7a1-fe03416ab23e)

As you can see on the capture, Motis recommends to take the bus at the Harteloire station, which is objectively further than the "Liberté Kérabecam" station. 

![Capture d’écran 2024-05-27 à 08 45 08](https://github.com/motis-project/motis/assets/1177762/a0dfa751-211b-4bee-99fc-ce6dac208bc3)

To reproduce, try these : 
start : 48.387723;-4.480754999999999
destination : 48.389241;-4.523912999999999

I suspected the problem was the PPR module : if the first bus stop was inaccessible per the profile, it could make the user walk more to the next one. But [on my instance](https://cartes.app/?allez=Point+sur+la+carte%7C%7C-4.4811%7C48.3877-%3EPoint+sur+la+carte%7C%7C-4.5259%7C48.3941&mode=commun&choix=3#13.12/48.3909/-4.52318), where I set up the motis call to use the "distance_only" PPR profile, I get the same result. 

![Capture d’écran 2024-05-27 à 09 01 10](https://github.com/motis-project/motis/assets/1177762/3ea2afb3-e7f3-4746-9b0c-38b117cbec1c)

------------

Case 2 : here is another strange case. 

start : "gare de brest" 
destination : 48.400386;-4.527864

![Capture d’écran 2024-05-27 à 08 49 43](https://github.com/motis-project/motis/assets/1177762/c6e5ddc3-6d95-4bbc-a03f-86af3a31c30c)

![Capture d’écran 2024-05-27 à 08 50 56](https://github.com/motis-project/motis/assets/1177762/ec5713d9-dcb2-4a93-9915-2a6aa1138d78)

Here, one obvious suggestion is the bus 1. Bus as you can see in these captures, Motis tells me to take another bus, the 02B, to stop at "Foyer du marin", then walk to the 1:Dupleix even though there is 1:Liberté Branda 20 meters from 02B:Foyer du marin ! 

Again, my hypothesis was that PPR can't make me walk to the 1:Liberté Branda because it's drawn on a non pedestrian lawn, but changing the request to an origin 10 m from that bus stop lets me use the bus stop :sweat_smile: Set the origin to 48.390386;-4.483115 and destination to 48.400386;-4.527864.

As I was tryng to make the first request again to zoom on the strange bus02b -> walk -> bus1 start connection, I got another even more absurd result ! 
![Capture d’écran 2024-05-27 à 09 10 01](https://github.com/motis-project/motis/assets/1177762/be3e5d2e-0dc7-42ce-883e-48e9e92895ab)

Then I discovered that setting the origin to a manual point that is 5 m away from "gare de brest" makes the recommendation work : walk to the 1:Liberté branda the bus 1 all the way :heavy_check_mark:  

It could be that Motis doesn't know how to leave "Gare de Brest" without a bus through transfers... this would "solve" the first problem, but not the problem of my first scenario (walk past 4:Liberté Kerabecam to Harteloire). It doesn't explain the absurd 02b->01 connection either. 

Thanks for your help !

**Comment by felixguendling** [comment]
> which is objectively further than the "Liberté Kérabecam" station

The current status of the implementation does not minimize walking time at all. So if there are two connections A=(1h of which 2min are walking, 2 transfers) and B=(59min of which 30min is walking, 2 transfers), then B would win and A would not be displayed. This applies to transfers as well as to the first and last leg.

We plan to improve this in the next few months.

**Comment by laem** [comment]
Thanks. So if I understand well, on the last capture, the algo doesn't discriminate between : 
- walking 15 minutes to the Université bus stop
- walking 1 minute to the Liberté Branda stop and then wait there for 14 minutes until the bus leaves

Could setting a slower walk speed in the PPR profile work to avoid this kind of results that would obviously be judged as sub-optimal by most users ?

**Comment by felixguendling** [comment]
In some cases, this quickfix would probably help until we have the full version implemented.

**Comment by laem** [comment]
Awesome, thanks :)

**Comment by mority** [comment]
Thank you for reporting :-) please do let us know if you encounter any further issues.

**Comment by laem** [comment]
Do I need to active a certain option to use this new feature ? Or just to use the latest motis release publisued on the releases page ? 

Then I'll let you know :)

**Comment by felixguendling** [comment]
There's no additional option. It's now the default behaviour to shorten the footpaths where possible.
