### ISSUE TITLE
Referencing multiple GTFS sources in config.ini

### ISSUE THREAD

**Issue by luckyhandler** [motis-project/motis#511]
I'd like to enhance the GTFS data Motis is relying on by one or two other resources. I therefore have 2 questions:

- Is it possible in the first place or do I have to merge it using another tool?
- How do I include different datasets into my `config.ini`?

I tried it like 

```ini
# Configure datasets
[import]
paths=schedule-de:/input/schedule_germany
paths=schedule-vgn:/input/schedule_vgn
paths=osm:/input/osm.pbf
```

Or also 

```ini
# Configure datasets
[import]
paths=schedule-de:/input/schedule_germany,schedule-vgn:/input/schedule_vgn
paths=osm:/input/osm.pbf
```

In both cases I get the error message during startup

`options error: unrecognised option 'ris.db'`.

How do I best approach this issue?

**Comment by felixguendling** [comment]
Can you please post your full configuration. `ris.db` is not part of your snippet.

```ini
[import]
paths=schedule-de:/input/schedule_germany
paths=schedule-vgn:/input/schedule_vgn
paths=osm:/input/osm.pbf
```

However, I guess VGN is part of Germany, so I'm not sure how this would help to enhance the GTFS data. It would probably produce lots of duplicates. So setting `nigiri.merge_duplicates` might help to some degree.

**Comment by luckyhandler** [comment]
My full config.ini is. I don't configure anything related to `ris.db`, do I?

``ìni
modules=nigiri
modules=intermodal
modules=osrm
modules=ppr

intermodal.router=nigiri

# Configure datasets
[import]
paths=schedule-de:/input/schedule_germany
paths=schedule-vgn:/input/schedule_vgn
paths=osm:/input/osm.pbf

# OSRM profiles (add more if needed)
[osrm]
profiles=/motis/osrm-profiles/car.lua

# Configure schedule range
[nigiri]
first_day=TODAY
num_days=31
default_timezone=Europe/Berlin
```

and I would like to add this to improve the data quality. So 
1. base file is complete Germany, 
2. then as VGN has a better data set overwrite the corresponding GTFS data

**Comment by luckyhandler** [comment]
I use `motis:0.12.5`

**Comment by felixguendling** [comment]
The Dockerfile is not up-to-date. I'll create a new release.

**Comment by luckyhandler** [comment]
So in general the approach is correct and the issue I have not related to the config.ini change but the motis version, right?

```ini
modules=nigiri
modules=intermodal
modules=osrm
modules=ppr

intermodal.router=nigiri

# Configure datasets
[import]
paths=schedule-de:/input/schedule_germany
paths=schedule-vgn:/input/schedule_vgn
paths=osm:/input/osm.pbf

# OSRM profiles (add more if needed)
[osrm]
profiles=/motis/osrm-profiles/car.lua

# Configure schedule range
[nigiri]
first_day=TODAY
num_days=31
default_timezone=Europe/Berlin
merge_duplicates=true
```

**Comment by luckyhandler** [comment]
With `motis:0.12.6` the `options error: unrecognised option 'ris.db'` error is gone.

Still, the `merge_duplicates=true` seems to be not accepted as parameter. So do I have to reference it differently?

**Comment by felixguendling** [comment]
I released a new version that does not have the `ris.db` variable set in the Docker base config.

`nigiri.match_duplicates=true` is the correct name.

**Comment by luckyhandler** [comment]
Seems to be working. Thanks for the immediate answer!

**Comment by luckyhandler** [comment]
thanks

**Comment by luckyhandler** [comment]
Can you tell me which indicators are used for merging?

**Comment by felixguendling** [comment]
- Stations from *different* datasets are considered equivalent if they are closer than 300m (constant can be changed [here](https://github.com/motis-project/nigiri/blob/29e632864c8f0ca25fd90c4f4181ba1b2a3aa184/src/loader/link_nearby_stations.cc#L12)).
- The stop sequence has to match (for each stop an equivalent stop from the other dataset) [here](https://github.com/motis-project/nigiri/blob/29e632864c8f0ca25fd90c4f4181ba1b2a3aa184/src/loader/merge_duplicates.cc#L103-L108)
- The first departure time has to match *exactly* [here](https://github.com/motis-project/nigiri/blob/29e632864c8f0ca25fd90c4f4181ba1b2a3aa184/src/loader/merge_duplicates.cc#L115-L118)
- And finally times are not allowed to deviate more than 1 minute per stop in the stop sequence [here](https://github.com/motis-project/nigiri/blob/29e632864c8f0ca25fd90c4f4181ba1b2a3aa184/src/loader/merge_duplicates.cc#L119).
