### ISSUE TITLE
Parking vs Park and Ride

### ISSUE THREAD

**Issue by ch33hau** [motis-project/motis#526]
Hi there,

I am currently using the parking module and have found that the routing works as expected.

However, I have a question: Is there a way to configure it to use only parking areas with the OSM tag `park_and_ride=yes`? Am I correct in understanding that Motis currently uses any parking areas tagged with `amenity=parking`?

Thanks,
Chee Hau

**Comment by felixguendling** [comment]
Currently, there's no way to configure it. But I guess it's easy to change the code if you want to try:
https://github.com/motis-project/motis/blob/c2cba9ef7a52f565588ba236ad3c9edd021df170/modules/parking/src/osm_parking_lots.cc#L44
