### ISSUE TITLE
Missing `railviz.tiles_redirect` option for demo ui?

### ISSUE THREAD

**Issue by nicolaswurtz** [motis-project/motis#527]
Hi! I would like to use an external tiles provider (my own with martin/maplibre) for demo ui, but the option tiles_redirect don't work anymore. Do you have any idea how I could use external tiles provider? Thx.

PS: I'm a BIG fan of this project!

**Comment by felixguendling** [comment]
Maybe hardcoding it in the `main.js` file would already do the job?

https://github.com/motis-project/motis/blob/c2cba9ef7a52f565588ba236ad3c9edd021df170/ui/web/js/main.js#L21

If you just want another map style, you can also try to set `?style=color`. The result looks like this (depending on `?style=` parameter and the lua profile used in the backend):
https://github.com/motis-project/motis/releases/tag/v0.11.30

**Comment by felixguendling** [comment]
Did this help? Otherwise, I would also be open to merge a PR to add this feature again to the nigiri module.

**Comment by nicolaswurtz** [comment]
Hey! Sorry for late response, yes, it works, not perfectly, there's some style & url formatting issues, but it works. Perhaps I'll try to make a PR to enable it with config file (and inject specific style, why not?).
Thank you for your help!
