### ISSUE TITLE
Web interface is always displayed in German

### ISSUE THREAD

**Issue by yvan-algoo** [motis-project/motis#531]
Hi,

The web interface (https://europe.motis-project.de/ and https://routing.spline.de) is always displayed in German:

- I tried with both Firefox and Chromium, and verified that my `Accept-Language` HTTP request headers only mention French and English. 
- I can not find a button in the UI to change the language.

However, from what I understand, English and French translations are available (https://github.com/motis-project/motis/tree/master/ui/web/src/Localization): am I missing something?

Regards,
Yvan

**Comment by felixguendling** [comment]
Currently, there's no detection of the language but you can use the `lang` query parameter:
https://europe.motis-project.de/?lang=fr
https://europe.motis-project.de/?lang=en

**Comment by yvan-algoo** [comment]
Thanks @felixguendling! Using the `lang` parameter in the URL is a good workaround :-)

I do not know if you want to close this issue or not, so I let it open.

**Comment by felixguendling** [comment]
We can leave it open until we have language detection working. Although not in the current UI version as this one is deprecated. But I'm working on a new one (currently only used for debugging).

**Comment by felixguendling** [comment]
Still relevant with v2 as it's not translated at all yet (TODO).

**Comment by felixguendling** [comment]
For now, we use the detected language from the browser:

https://github.com/motis-project/motis/blob/d773eac4c6af5256780310f1d3784b7be1900525/ui/src/lib/AddressTypeahead.svelte#L34

I'm open to add a button that let's the user change the language.
