### ISSUE TITLE
Exclude some lines in an API request

### ISSUE THREAD

**Issue by matteoferrux** [motis-project/motis#551]
Hi,
Ilevia, our public transport network here in Lille, **sometimes experiences major breakdowns and regular outages**, particularly on the metro and tramway lines, and I'm currently working on user interaction with the route engine via the MOTIS API. I'd like to know if it's possible to exclude certain lines when calculating a route (the lines in question would be brought up via an internal API) to avoid sending our users to lines that are out of order.

Thank you in advance for your reply!

**Comment by felixguendling** [comment]
If I understand the use case correctly, the best way would be to cancel those lines using GTFS-RT. You can have several GTFS-RT endpoints for the same GTFS-static file. With one you could produce cancellation messages for every trip you want to remove from the routing.

**Comment by matteoferrux** [comment]
But my problem is that Ilevia doesnt have any GTFS-RT for the metro because the VAL system is too old for that :/

**Comment by matteoferrux** [comment]
So I'd have to produce a GTFS-RT myself when there's a technical problem?

**Comment by matteoferrux** [comment]
Hello,
First of all, allow me to thank you for your various replies. The rude man that I am did not reply and I apologize!

After a few days of research on how to generate a GTFS-RT stream, I found out how to do it and how to customize it. I wanted to ask you: what “alerts” does Motis support? I've tried to make an alert for the complete line (route_id) but it doesn't seem to be supported. Should I make an alert for each trip_id?

Thanks in advance!
Mattéo

**Comment by felixguendling** [comment]
If you want to exclude a trip completely, the alert option is not the right one. Currently, MOTIS doesn't support alerts yet. But if it would, it would still show the connections (just with an alert). What you want is to cancel the trip with a TripUpdate (setting it to canceled).

**Comment by matteoferrux** [comment]
Thanks for all the information. I tried to cancel a trip of the M2 line indicated in the GTFS, but the console always returns me the same error message: “[error][rt.gtfs.unsupported] unsupported no trip update (tag=ilevia, id=1)”

The GTFS-RT stream in JSON format:

```
{
    "header": {
      "gtfsRealtimeVersion": "2.0",
      "incrementality": "FULL_DATASET",
      "timestamp": "1728335101"
    },
    "entity": [
      {
        "id": "1",
        "trip_update": {
          "trip": {
            "trip_id": "5174012",
            "start_time": "22:36:00",
            "start_date": "20241007",
            "schedule_relationship": "CANCELED"
          }
        }
      }
    ]
}
``` 

Thanks for your help !

**Comment by felixguendling** [comment]
The structure is a bit different. You can copy it from here:
https://github.com/motis-project/nigiri/blob/73e1b52c2e165d05becf951fcb5d65380c37aa99/test/rt/skip_test.cc#L67-L105

Addresses are provided by the `adr` module. They should appear if you enable it.
(although those that you show seem a bit weird - not sure what you searched for)

**Comment by matteoferrux** [comment]
Good evening,
I followed your recommendations and copied the structure from the file you indicated above. In fact, I can see that the services concerned are indicated in real time in Motis (with the +0), but the stops I indicate in SKIPPED have no effect and so the journey is still not cancelled.

The RT stream link before conversion to protobuf : https://api.mobilille.fr/gtfs/rt_stream.php

Thanks for the addresses, it works fine!
Thanks for your help

**Comment by felixguendling** [comment]
Seems like you didn't set the schedule relationship to canceled like before? The `SKIP` was not relevant (canceling the whole trip is more important than skipping stops). I just referred to the structure + naming, sorry.

**Comment by matteoferrux** [comment]
My misunderstanding! ^^
I'll try with the same structure as before, changing the variable names and come back to tell you what ;)

**Comment by matteoferrux** [comment]
```
{
  "header": {
    "gtfsRealtimeVersion": "2.0",
    "incrementality": "FULL_DATASET",
    "timestamp": 1728503047
  },
  "entity": [
    {
      "id": "idd5174011",
      "tripUpdate": {
        "trip": {
          "tripId": "5174011",
          "startTime": "21:38:48",
          "startDate": "20241009",
          "scheduleRelationship": "CANCELED"
        }
      }
    }
  ]
}
``` 
I've tried with this structure. Same as before. The +0 appears but no action.

**Comment by matteoferrux** [comment]
I've got it! It works. I had to replace CANCELED with the value 3. I relied on the documentation, replaced it and now all the services concerned have been deleted.

![image](https://github.com/user-attachments/assets/fb76a5d9-3425-4728-92dc-3f1ef42213fe)

**Comment by felixguendling** [comment]
Perfect! :tada:
