### ISSUE TITLE
OpenAPI documentation for routing modes not clear

### ISSUE THREAD

**Issue by SebastiaanWouters** [motis-project/motis#629]
I am trying to calculate the most optimal routes between two points (given by coordinates) by car.
By reading the openapi documentation it doesn't become clear if i should use the one-to-many endpoint for this or the plan endpoint? 
- **plan endpoint**: i can query the endpoint like this: http://localhost:8080/api/v1/plan?fromPlace=51.2093,3.2247&toPlace=50.8798,4.7005&mode=CAR, but this seems to always return an empty array of itineraties. It seems like this endpoint is made to support transit modes, but this is not explicitly stated in the oppenapi docs?
- **one-to-many enpoint**: i can query the endpoint like this: http://localhost:8080/api/v1/one-to-many?one=51.2093;3.2247&many=51.0551;3.7165&mode=CAR&max=40000&maxMatchingDistance=600&arriveBy=false, but this only returns a duration, more extended information would be useful.

```
responses:
        200:
          description: |
            A list of distance + duration pairs.
            If no path was found, the object doesn't contain distance and duration.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Duration'
```
The openapi description mentions that this should return a pair of distance and duration, which doesn't seem to match my results.

I am wondering if it is possible to get a list or singleton of path,distance,duration between two given points by car?

**Comment by felixguendling** [comment]
The `plan` endpoint is the right approach. It's just not yet implemented. We're working on it.

**Comment by felixguendling** [comment]
Should work now for beta.8: 
https://github.com/motis-project/motis/releases/tag/v2.0.0-beta.8

Example:
https://europe.motis-project.de/api/v1/plan?fromPlace=51.2093,3.2247&toPlace=50.8798,4.7005&mode=CAR&maxDirectTime=7200

New parameter `maxDirectTime` controls maximum direct distance. You can find direct connections (if they were found) in the `PlanResponse.direct` attribute.

> [!IMPORTANT]
> When combining requests for `TRANSIT,CAR` with long `maxDirectTime` you won't find `TRANSIT` connections that are longer than `CAR` connections. If you don't want to compare them, you'd have to do two separate requests. At least with the current status of the implementation...

The UI doesn't have a `CAR` mode button yet, but you can just copy&paste `PlanResponse` JSON on the web UI to visualize journeys:

![image](https://github.com/user-attachments/assets/8074c6fe-d631-406f-9b0f-f11a6fc855db)

**Comment by felixguendling** [comment]
Note that `maxDirecTime` is hopefully a temporary solution. As soon as we have a A* or bidirectional A* implementation, we don't need this parameter anymore in terms of a stopping criterion for the shortest path algorithm.

**Comment by felixguendling** [comment]
You need the `street_routing=true` configuration flag.
Please check https://github.com/motis-project/motis/blob/master/docs/setup.md for a full list of options.
