### ISSUE TITLE
Is memory usage increased?

### ISSUE THREAD

**Issue by ch33hau** [motis-project/motis#650]
Hi there,

We are recently upgrading motis version from `v0.12.14` to `v0.12.18`, all configurations remained the same.
However, the memory usage seems increased a lot, especially when building the graph for osrm-* for Germany.

These are the modules that we are using: `--modules address gbfs intermodal nigiri osrm ppr tiles parking`.

Are you aware of this or do you have any suggestions regarding this?

(We are using a server that has max 64GB but the actual usable memory is about 58-60GB of memory) 

Thanks!

**Comment by felixguendling** [comment]
Closing as this issue targets the legacy version. We track only issues of version >= v2.
