### ISSUE TITLE
Support ssim format for flights?

### ISSUE THREAD

**Issue by Altonss** [motis-project/motis#652]
Data for airlines doesn't seem to available very often as gtfs formats.
I see that the ssim format seems to be used quite often, would it make sense to support it in motis? (see for example https://github.com/planarnetwork/ssim2gtfs to convert into gtfs)

**Comment by felixguendling** [comment]
Sounds interesting. Thank you! Is there any disadvantage to use the tool you linked and let MOTIS consume GTFS?

**Comment by felixguendling** [comment]
Since transitous (and most other MOTIS users) has a preprocessing pipeline anyway, using ssim2gtfs seems like the easiest solution for now. Let me know if any problems come up with this approach. Closing this for now. Reopen if any issues with conversions pop up.

**Comment by vkrause** [comment]
Asking from the Transitous perspective, are you aware of any publicly available SSIM datasets?
