### ISSUE TITLE
Optimistic walking path to the first stop

### ISSUE THREAD

**Issue by GerdC** [motis-project/motis#661]
Context: I can plug different routing servers into my app, this is a comparison of Motis (Transitous instance) with TRIAS (nvbw instance).

This is the same route visualised with both server responses.
Route is from near Charlottenplatz, Stuttgart, to Fernsehturm, Stuttgart, U7.
I'm always routing from coordinate to coordinate, not from stop to stop.

Motis shows a foot path with 1 minute duration:
endpoint https://routing.spline.de/api/?elm=IntermodalConnectionRequest (Transitous)
![Simulator Screenshot - iPad (10th generation) - 2024-11-16 at 13 31 51](https://github.com/user-attachments/assets/a0aa41db-e7a8-47c2-9109-6f098072985d)

Trias shows 5 minutes (I still have to write code to combine the 2 foot paths)
![Simulator Screenshot - iPad (10th generation) - 2024-11-16 at 13 31 20](https://github.com/user-attachments/assets/39674584-5457-4b55-b2c1-aba8473b41bd)

In this issue, I don't care a bout the rendered walking path, I care about the walking time.
NVBW TRIAS is right, I'm way too old to get this done In 1 minute.

I hope I'm in the right project with this issue.

**Comment by felixguendling** [comment]
Thank you for your report! :)

MOTIS v2 gives 9 minutes and also calculates the correct route including the underground part:

<img width="1418" alt="Screenshot 2024-11-16 at 15 51 29" src="https://github.com/user-attachments/assets/9a4f2a63-c7c4-4143-a74e-74db8638ac8f">
<img width="1350" alt="Screenshot 2024-11-16 at 15 51 45" src="https://github.com/user-attachments/assets/9ef312cd-b8c9-4f6d-88e4-def41ec85e9c">

For filing bug reports, please use MOTIS v2 beta.
Deployed for example here: https://europe.motis-project.de

Unfortunately, we don't have capacities to fix or backport fixes for the legacy version `v0.*`.

Closing as it looks okay in MOTIS v2. Let me know if I made a mistake with the start/destination coordinates.

**Comment by GerdC** [comment]
Confirmed with my Motis 2 implementation
![Simulator Screenshot - iPad (10th generation) - 2024-11-17 at 13 19 34](https://github.com/user-attachments/assets/ba699653-7fe7-4da9-891a-4b279ba0852f)

**Comment by felixguendling** [comment]
Perfect! :)
