### ISSUE TITLE
Some strings are not translated in interface

### ISSUE THREAD

**Issue by kalon33** [motis-project/motis#675]
When planning itineraries using latest MOTIS beta (on https://europe.motis-project.de), "transfers" is not translated, along, when you display the details, "START", "END" and walking information, that is in German, for example "8 min Fußweg (480 m)" between two trains for example (and with a different fontsize). Initial and last walking legs are properly translated (even if it would be great to set the order and format between "walk" translation and time and distance).

Thanks for your help!

**Comment by felixguendling** [comment]
https://github.com/motis-project/motis/commit/fc15f51aa59bf6101221b12e4daa0c2775638d76

I tried to improve it a big but feel free to make a PR to improve it even more :)

**Comment by felixguendling** [comment]
Should be translated now with [v2.0.0-beta.24](https://github.com/motis-project/motis/releases/tag/v2.0.0-beta.24). I used Google Translate for French, so please open a PR if that's not the correct translation. I hope all points in this issue have been addressed. If not please create a new issue or reopen.
