### ISSUE TITLE
error: too many trips out-of-the-box

### ISSUE THREAD

**Issue by miklcct** [motis-project/motis#684]
version: v2.0.0-beta.27
OSM used: London
GTFS used: National Rail GTFS + London DfT combined into one file

The UI, once started, shows 500 fetching trips and the log shows 2024-12-10T13:35:41Z [VERIFY FAIL] too many trips

**Comment by felixguendling** [comment]
https://github.com/motis-project/motis/releases/tag/v2.0.0-beta.28

limit increased to 12k, I hope this helps
