### ISSUE TITLE
Realtime fetch error: body limit exceeded

### ISSUE THREAD

**Issue by hannsadrian** [motis-project/motis#688]
Hey everyone, thank you for all the work on this amazing project!
I am currently experimenting with a setup to incorporate data from [gtfs.de](http://gtfs.de/), which already seems to work quite nice.
However when I try to configure their realtime feed, I get the following error:

```
[info][2024-12-21T15:56:03Z+0100][timer.cc:9] [rt update] starting
2024-12-21T15:56:03Z | [error][motis.rt                      ] RT FETCH ERROR: tag=gtfs-out, error=body limit exceeded [beast.http:9 at /Users/runner/work/motis/motis/deps/boost/./boost/beast/http/impl/basic_parser.ipp:493:60 in function 'void boost::beast::http::basic_parser<false>::finish_header(error_code &, std::false_type) [isRequest = false]']
2024-12-21T15:56:03Z | [info][motis.rt                      ] rt update stats for tag=gtfs-out, url=https://realtime.gtfs.de/realtime-free.pb: parser_error=1, no_header=1
[info][2024-12-21T15:56:03Z+0100][timer.cc:18] [rt update] finished (167.876ms)
```

My config for the dataset part looks like this:

```
  datasets:
    gtfs-out:
      path: gtfs-out
      default_bikes_allowed: false
      rt:
        - url: https://realtime.gtfs.de/realtime-free.pb
```

The realtime-free.pb file is about 8mb large (depending on the time of day).

Could this be an error in the config or is the GTFS-RT support not capable of larger files?

**Comment by felixguendling** [comment]
should be fixed with 2.0.4

thank you for reporting!

please reopen if it's not fixed

**Comment by hannsadrian** [comment]
Thank you very much, it seems to work now.

One thing I noticed in the logs:
```
ignoring unsupported "alert" field (tag=gtfs-out, id=189615al2878936129)
unsupported: no "trip_update" field (tag=gtfs-out, id=189615al2878936129), skipping message
rt update stats for tag=gtfs-out, url=https://realtime.gtfs.de/realtime-free.pb: total_entities=5806, total_entities_success=1850 (31.8636%), unsupported_alert=3956 (68.1364%), no_trip_update=3956 (68.1364%)
```

Is support for alerts planned? It would be something I'd be happy to contribute to.

**Comment by felixguendling** [comment]
> Is support for alerts planned?

Yes.


> It would be something I'd be happy to contribute to.

Cool! :) You can start implementation in the https://github.com/motis-project/nigiri repository. The information would be stored in the `rt_timetable` struct.
