### ISSUE TITLE
MOTIS 0.3 Linux Release - dead download link

### ISSUE THREAD

**Issue by DerItalienischePhysiker** [motis-project/motis#84]
Following the link to the binaries for MOTIS 0.3 for Linux from either the Releases page or the MOTIS installation documentation (https://github.com/motis-project/motis/releases/download/v0.3/motis-linux.tar.bz2) results in the following XML being delivered:

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>255657224/02b79b80-ab42-11ea-87d7-9b3c825d91ca</Key>
<RequestId>52F77FA3615883A7</RequestId>
<HostId>nfBFH/+ShebyGr+bPGCunhIjuKRa16TazwIRYBFGrMUqM/osowe8jGIvVjuPE1ZFyzBS4ooaSB0=</HostId>
</Error>
```

The Windows and MAC build are downloadable without issues, instead.

**Comment by felixguendling** [comment]
Thank you. I uploaded the current build artifact from the master branch.

**Comment by DerItalienischePhysiker** [comment]
Now the link works as intended, thank you very much!

**Comment by felixguendling** [comment]
You're welcome! Please feel free to open more issues if you hit any problems.
You are probably one of the very first people (besides us developers) to try to MOTIS.

**Comment by DerItalienischePhysiker** [comment]
I'll surely do it, in case of need! I started having a look at MOTIS as an alternative to OpenTripPlanner and Google Maps, and wanted to try out how well it fares compared with both of them, especially in terms of intermodal routing. The demo seems promising (and building it from the source on the master branch wasn't too hard, on Ubuntu 20.04). In case of issues or need for clarifications, I will open other tickets.
