### ISSUE TITLE
Understanding GTFS-RT support in MOTIS v0.3

### ISSUE THREAD

**Issue by DerItalienischePhysiker** [motis-project/motis#97]
I'm trying to understand where/how MOTIS downloads real-time GTFS-RT updates. Since the Swiss Open Platform Data requires an API key to access the real time updates, I was surprised to see that MOTIS was able to keep track of bus delays and positions without me using one, even on my local copy

Since I have a personal API key for the Swiss Open Data Platform Mobility, I wanted to understand where I can add it and how to edit the connection details for the updates. I have browsed the C++ source code, but I couldn't get a good idea on where to look.

As per #73, currently MOTIS uses external scripting to update GTFS-RT. Where are those scripts located? The target version for this question is MOTIS release v0.3.

**Comment by felixguendling** [comment]
Setting up GTFS-RT support for Switzerland is unfortunately a bit more complicated. We use the HAFAS Rohdaten data because they are higher quality and MOTIS support for HAFAS Rohdaten data is better than the GTFS support (see open issues regarding GTFS). It could work with GTFS data too, but I haven't tested this in a while.

If you use HAFAS Rohdaten, you need the GTFS trip IDs from the GTFS dataset. You can export them with a config like this:

```
init=/ris/write_gtfs_trip_ids
mode=init
modules=ris

[import]
...
```

Then in your main instance config:

```
...

[ris]
gtfs_trip_ids=/path/to/gtfs_trips.raw
gtfsrt.is_addition_skip_allowed=false
instant_forward=true
input=/path/to/gtfsrt_download_folder
...
```

This way, MOTIS can match GTFS trip updates to HAFAS Rohdaten data.

To download GTFS RT updates into the download folder, you can use this script:

```
#!/bin/bash
while true; do
  filename="$(date +%Y%m%d-%H%M%S).pb"
  curl -X GET -H "Content-type: application/octet-stream" -H "Authorization: ${OTD_KEY}" -o "$filename" https://api.opentransportdata.swiss/gtfs-rt
  echo "$i" "$filename"
  curl --insecure https://localhost:8080/ris/read
  sleep 30
done
```

Sorry, it's a bit complicated. Maybe it's easier to try GTFS + GTFS-RT instead of HRD + GTFS-RT first and see if it does something.

**Comment by DerItalienischePhysiker** [comment]
No problems and thanks for the thorough explanation. So, since MOTIS v0.3 isn't using GTFS-RT for the real-time information by default (with this I mean, just by using the release as-is with a suitable OpenStreetMap graph), how are the real time data/positions of the vehicles I can see in the web interface currently retrieved? Which data source is used for those real-time updates?

**Comment by felixguendling** [comment]
The positions of the vehicles on the map are interpolated from the schedule timetable data. So they are not "real-time". MOTIS is only operating in real-time mode if you have at least some vehicles with "+0" (real-time update says on time) or "+5"  (5 min delay) when you hover over the vehicles on the map.

Without configuring the 'ris' module and without the bash/curl script above, MOTIS only uses schedule timetable data.

MOTIS only uses delay data and does a interpolation of the path on the map to draw the vehicle. It cannot handle GPS position updates of vehicles.

**Comment by DerItalienischePhysiker** [comment]
Perfectly clear, thanks a lot. I will try to setup the RIS module and see how it works.

**Comment by DerItalienischePhysiker** [comment]
I have tried the above and have some troubles setting this up:

1. I have downloaded both the Hafas and GTFS timetables
2. I added the GTFS timetable to the `paths`
3. Edited the configuration file with the lines:
```
server.static_path=motis/web

init=/ris/write_gtfs_trip_ids
mode=init
modules=ris

[import]
paths=data/gtfs
paths=data/switzerland-latest.osm.pbf
data_dir=data
```
4. the `gtfs_trips.raw` file is created as expected. It weighs around 67MB
5. I then switched the path to the Hafas timetable and edited in the suitable `[ris]` setup
6. I started MOTIS. The program crashes after loading the output line `[info][2020-09-02T15:40:14Z+0000][logging.cc:28] [loading OSRM dataset: bike] finished (20085.7ms)` with the message `initialization error: module: malformed message`
7. If I remove the [ris] portion of the configuration file, this doesn't happen and the program starts, albeit without real time information.

Here in the following, the complete config file I use for this to happen:
```
server.static_path=motis/web

[import]
paths=data/hrd
paths=data/switzerland-latest.osm.pbf
data_dir=data

[osrm]
profiles=motis/osrm-profiles/car.lua
profiles=motis/osrm-profiles/bike.lua
profiles=motis/osrm-profiles/bus.lua

[ppr]
profile=motis/ppr-profiles/default.json

[tiles]
profile=motis/tiles-profiles/background.lua

[ris]
gtfs_trip_ids=data/realtime/gtfs_trips.raw
gtfsrt.is_addition_skip_allowed=false
instant_forward=true
input=data/realtime/gtfsrt
```
`data/hrd` is the folder which contains the Hafas timetable, while `data/realtime/gtfs_trips.raw` is the 67MB file produced by the GTFS export. Am I missing something trivial?

**Comment by DerItalienischePhysiker** [comment]
I confirm that the code changes shown in the commit for #98 fixed this issue and that now I can use real time data with MOTIS following the process outlined here: https://github.com/motis-project/motis/issues/97#issuecomment-684616524. Thanks for the quick solution!
